server:
  port: 81

spring:
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss

  datasource:
    username: root
    password: biubiu
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tv?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8


mybatis-plus:
  type-aliases-package: cn.duzou.log.*.entity
  mapper-locations: classpath:mapper/*/*/*.xml
  configuration:
    # 开启sql日志
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    jdbc-type-for-null: null
  global-config:
    banner: false
    db-config:
      select-strategy: NOT_EMPTY